# Generated by Django 3.0.4 on 2020-03-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(max_length=200)),
                ('bankName', models.CharField(max_length=200)),
                ('annualFee', models.IntegerField()),
                ('rewardsType', models.CharField(max_length=200)),
                ('rewardValue', models.IntegerField()),
                ('rewardsDisplay', models.TextField()),
                ('groceryMultiplier', models.IntegerField()),
                ('restMultiplier', models.IntegerField()),
                ('travelMultiplier', models.IntegerField()),
                ('otherMultiplier', models.IntegerField()),
                ('gasMultiplier', models.IntegerField()),
                ('valOfSingRe', models.IntegerField()),
                ('APR', models.IntegerField()),
                ('bonusDisplay', models.TextField()),
                ('bonusValue', models.IntegerField()),
                ('link', models.TextField()),
                ('creditScore', models.IntegerField()),
            ],
        ),
    ]
