# Generated by Django 3.0.4 on 2020-04-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bonusMinimumSpend',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='bonusSpendMonths',
            field=models.IntegerField(null=True),
        ),
    ]
