# Generated by Django 2.2.7 on 2020-04-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='everythingElse',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='rewardValue',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
