# Generated by Django 3.0.4 on 2020-04-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20200422_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bonusMinimumSpend',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='bonusSpendMonths',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
