# Generated by Django 2.2.7 on 2020-04-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20200401_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rewardValue',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
