# Generated by Django 2.2.7 on 2020-04-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20200401_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='restMultiplier',
            new_name='restaurantMultiplier',
        ),
        migrations.RemoveField(
            model_name='card',
            name='valOfSingRe',
        ),
        migrations.AlterField(
            model_name='card',
            name='creditScore',
            field=models.CharField(max_length=200),
        ),
    ]
