# Generated by Django 2.2.7 on 2020-04-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20200413_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='otherMultiplier',
        ),
    ]
